"""
Report generation module for SyFi AI data profiling.

This module handles the generation of various report formats including
HTML, JSON, and markdown reports with banking-specific visualizations.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional
import html

class ProfileReporter:
    """
    Generates comprehensive reports from profiling data.
    
    Supports multiple output formats and provides banking-specific
    report templates and visualizations.
    """
    
    def __init__(self, output_dir: Path):
        """
        Initialize reporter with output directory.
        
        Args:
            output_dir: Directory where reports will be saved
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
    
    def generate_report(self, profile_data: Dict[str, Any], 
                       format: str = 'html',
                       filename: Optional[str] = None) -> Path:
        """
        Generate a comprehensive report from profile data.
        
        Args:
            profile_data: Complete profiling results dictionary
            format: Output format ('html', 'json', 'markdown')
            filename: Optional custom filename
            
        Returns:
            Path to generated report file
        """
        if not filename:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f'banking_profile_report_{timestamp}'
        
        if format == 'html':
            return self._generate_html_report(profile_data, filename)
        elif format == 'json':
            return self._generate_json_report(profile_data, filename)
        elif format == 'markdown':
            return self._generate_markdown_report(profile_data, filename)
        else:
            raise ValueError(f"Unsupported format: {format}")
    
    def _generate_html_report(self, profile_data: Dict[str, Any], filename: str) -> Path:
        """Generate HTML report with banking-specific styling."""
        html_content = self._build_html_template(profile_data)
        
        output_path = self.output_dir / f"{filename}.html"
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return output_path
    
    def _generate_json_report(self, profile_data: Dict[str, Any], filename: str) -> Path:
        """Generate JSON report."""
        # Convert any non-serializable objects to strings
        serializable_data = self._make_json_serializable(profile_data)
        
        output_path = self.output_dir / f"{filename}.json"
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(serializable_data, f, indent=2, default=str)
        
        return output_path
    
    def _generate_markdown_report(self, profile_data: Dict[str, Any], filename: str) -> Path:
        """Generate Markdown report."""
        md_content = self._build_markdown_content(profile_data)
        
        output_path = self.output_dir / f"{filename}.md"
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        return output_path
    
    def _build_html_template(self, profile_data: Dict[str, Any]) -> str:
        """Build complete HTML report template."""
        summary = profile_data.get('summary', {})
        banking_metrics = profile_data.get('banking_metrics', {})
        customer_profiles = profile_data.get('customer_profiles', {})
        data_quality = profile_data.get('data_quality', {})
        
        return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SyFi AI Banking Data Profile Report</title>
    <style>
        {self._get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>🏦 SyFi AI Banking Data Profile Report</h1>
            <p class="subtitle">Comprehensive Analysis of Synthetic Banking Database</p>
        </header>
        
        <main>
            {self._build_summary_section(summary)}
            {self._build_banking_metrics_section(banking_metrics)}
            {self._build_customer_profiles_section(customer_profiles)}
            {self._build_data_quality_section(data_quality)}
        </main>
        
        <footer class="footer">
            <p>Generated by SyFi AI Data Profiler on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </footer>
    </div>
</body>
</html>
        """
    
    def _get_css_styles(self) -> str:
        """Get CSS styles for HTML report."""
        return """
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        .header { text-align: center; margin-bottom: 40px; padding: 30px 0; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-radius: 10px; }
        .header h1 { font-size: 2.5em; margin-bottom: 10px; }
        .subtitle { font-size: 1.2em; opacity: 0.9; }
        
        section { margin-bottom: 40px; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h2 { color: #2c3e50; margin-bottom: 20px; font-size: 1.8em; }
        
        .metrics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }
        .metric-card { background: #f8f9fa; padding: 20px; border-radius: 8px; text-align: center; border-left: 4px solid #3498db; }
        .metric-value { font-size: 2em; font-weight: bold; color: #2c3e50; }
        .metric-label { color: #7f8c8d; margin-top: 5px; }
        
        .alert { background: #e3f2fd; border-left: 4px solid #2196f3; padding: 15px; margin: 20px 0; border-radius: 4px; }
        .alert-info { background: #e8f5e8; border-left-color: #4caf50; }
        
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f5f5f5; font-weight: 600; }
        tr:hover { background: #f9f9f9; }
        
        .progress-bar { background: #ecf0f1; border-radius: 10px; overflow: hidden; margin: 5px 0; }
        .progress-fill { height: 20px; background: linear-gradient(90deg, #3498db, #2ecc71); transition: width 0.3s ease; }
        
        .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; color: #7f8c8d; text-align: center; }
        """
    
    def _build_summary_section(self, summary) -> str:
        """Build the summary section with key metrics."""
        # Handle both dataclass and dict formats  
        if hasattr(summary, 'to_dict'):
            # It's a dataclass
            db_path = str(summary.database_path)
            total_customers = summary.total_customers
            total_accounts = summary.total_accounts
            total_transactions = summary.total_transactions
            database_size_kb = summary.database_size_kb
            unique_profiles = summary.unique_profiles
            analysis_date = summary.analysis_date
            date_range = summary.date_range
        else:
            # It's a dictionary
            db_path = str(summary.get('database_path', ''))
            total_customers = summary.get('total_customers', 0)
            total_accounts = summary.get('total_accounts', 0)
            total_transactions = summary.get('total_transactions', 0)
            database_size_kb = summary.get('database_size_kb', 0)
            unique_profiles = summary.get('unique_profiles', 0)
            analysis_date = summary.get('analysis_date', datetime.now())
            date_range = summary.get('date_range')
            
            # Parse date if it's a string
            if isinstance(analysis_date, str):
                analysis_date = datetime.fromisoformat(analysis_date)
        
        return f"""
        <section class="summary-section">
            <h2>📊 Database Overview</h2>
            
            <div class="metrics-grid">
                <div class="metric-card">
                    <div class="metric-value">{total_customers:,}</div>
                    <div class="metric-label">Total Customers</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{total_accounts:,}</div>
                    <div class="metric-label">Total Accounts</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{total_transactions:,}</div>
                    <div class="metric-label">Total Transactions</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{database_size_kb:.1f} KB</div>
                    <div class="metric-label">Database Size</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{unique_profiles}</div>
                    <div class="metric-label">Unique Profiles</div>
                </div>
            </div>
            
            <div class="alert alert-info">
                <strong>Database:</strong> {html.escape(db_path)}<br>
                <strong>Analysis Date:</strong> {analysis_date.strftime('%Y-%m-%d %H:%M:%S')}
                {f'<br><strong>Transaction Period:</strong> {date_range[0]} to {date_range[1]}' if date_range else ''}
            </div>
        </section>
        """
    
    def _build_banking_metrics_section(self, metrics: Dict[str, Any]) -> str:
        """Build banking metrics section."""
        if not metrics:
            return "<section><h2>🏪 Banking Metrics</h2><p>No banking metrics available.</p></section>"
        
        html_content = "<section><h2>🏪 Banking Metrics</h2>"
        
        # Account metrics
        account_metrics = metrics.get('account_metrics', {})
        if account_metrics:
            html_content += "<h3>Account Analysis</h3>"
            
            account_dist = account_metrics.get('account_type_distribution', {})
            if account_dist:
                html_content += """
                <table>
                    <thead>
                        <tr><th>Account Type</th><th>Count</th><th>Percentage</th><th>Avg Balance</th></tr>
                    </thead>
                    <tbody>
                """
                
                for acc_type, data in account_dist.items():
                    html_content += f"""
                        <tr>
                            <td>{acc_type.title()}</td>
                            <td>{data.get('count', 0)}</td>
                            <td>{data.get('percentage', 0)}%</td>
                            <td>${data.get('avg_balance', 0):,.2f}</td>
                        </tr>
                    """
                
                html_content += "</tbody></table>"
        
        # Transaction metrics
        transaction_metrics = metrics.get('transaction_metrics', {})
        if transaction_metrics and 'total_transactions' in transaction_metrics:
            html_content += "<h3>Transaction Analysis</h3>"
            
            # Transaction summary
            total_tx = transaction_metrics.get('total_transactions', 0)
            html_content += f"<p><strong>Total Transactions:</strong> {total_tx:,}</p>"
            
            # Transaction type distribution
            type_dist = transaction_metrics.get('transaction_type_distribution', {})
            if type_dist:
                html_content += """
                <h4>Transaction Types</h4>
                <table>
                    <thead>
                        <tr><th>Transaction Type</th><th>Count</th><th>Percentage</th></tr>
                    </thead>
                    <tbody>
                """
                for tx_type, count in type_dist.items():
                    percentage = (count / total_tx * 100) if total_tx > 0 else 0
                    html_content += f"""
                        <tr>
                            <td>{tx_type.title()}</td>
                            <td>{count}</td>
                            <td>{percentage:.1f}%</td>
                        </tr>
                    """
                html_content += "</tbody></table>"
            
            # Monthly patterns
            monthly_patterns = transaction_metrics.get('monthly_patterns', {})
            if monthly_patterns:
                html_content += """
                <h4>Monthly Transaction Patterns</h4>
                <table>
                    <thead>
                        <tr><th>Month</th><th>Transaction Count</th><th>Total Volume</th><th>Avg Amount</th></tr>
                    </thead>
                    <tbody>
                """
                for month, data in monthly_patterns.items():
                    html_content += f"""
                        <tr>
                            <td>{month}</td>
                            <td>{data['transaction_count']}</td>
                            <td>${data['total_volume']:,.2f}</td>
                            <td>${data['avg_amount']:,.2f}</td>
                        </tr>
                    """
                html_content += "</tbody></table>"
        
        html_content += "</section>"
        return html_content
    
    def _build_customer_profiles_section(self, customer_profiles: Dict[str, Any]) -> str:
        """Build customer profiles section."""
        if not customer_profiles:
            return "<section><h2>👥 Customer Profiles</h2><p>No customer profile data available.</p></section>"
        
        html_content = "<section><h2>👥 Customer Profiles</h2>"
        
        profile_distribution = customer_profiles.get('profile_distribution', {})
        if profile_distribution:
            html_content += """
            <table>
                <thead>
                    <tr><th>Profile Type</th><th>Count</th><th>Percentage</th></tr>
                </thead>
                <tbody>
            """
            
            for profile, data in profile_distribution.items():
                if profile and profile != 'NULL':
                    # Handle different data formats (dict vs int)
                    if isinstance(data, dict):
                        count = data.get('count', 0)
                        percentage = data.get('percentage', 0)
                    else:
                        # data is just a count
                        count = data
                        percentage = 0
                    
                    html_content += f"""
                        <tr>
                            <td>{html.escape(str(profile))}</td>
                            <td>{count}</td>
                            <td>{percentage:.1f}%</td>
                        </tr>
                    """
            
            html_content += "</tbody></table>"
        
        html_content += "</section>"
        return html_content
    
    def _build_data_quality_section(self, data_quality: Dict[str, Any]) -> str:
        """Build data quality assessment section."""
        if not data_quality:
            return "<section><h2>✅ Data Quality</h2><p>No data quality assessment available.</p></section>"
        
        html_content = "<section><h2>✅ Data Quality</h2>"
        
        # Overall quality score
        overall_score = data_quality.get('overall_quality_score', 0)
        html_content += f"""
        <div class="alert">
            <strong>Overall Quality Score: {overall_score:.1f}%</strong>
            <div class="progress-bar">
                <div class="progress-fill" style="width: {overall_score}%"></div>
            </div>
        </div>
        """
        
        # Quality issues
        quality_issues = data_quality.get('quality_issues', {})
        if quality_issues:
            html_content += "<h3>Quality Issues</h3><ul>"
            for table, issues in quality_issues.items():
                if issues:
                    html_content += f"<li><strong>{table}:</strong> {len(issues)} issues found</li>"
            html_content += "</ul>"
        
        html_content += "</section>"
        return html_content
    
    def _build_markdown_content(self, profile_data: Dict[str, Any]) -> str:
        """Build markdown report content."""
        summary = profile_data.get('summary', {})
        banking_metrics = profile_data.get('banking_metrics', {})
        
        # Extract summary data
        if hasattr(summary, 'to_dict'):
            total_customers = summary.total_customers
            total_accounts = summary.total_accounts
            total_transactions = summary.total_transactions
        else:
            total_customers = summary.get('total_customers', 0)
            total_accounts = summary.get('total_accounts', 0)
            total_transactions = summary.get('total_transactions', 0)
        
        md_content = f"""# SyFi AI Banking Data Profile Report

Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Database Overview

- **Total Customers:** {total_customers:,}
- **Total Accounts:** {total_accounts:,}
- **Total Transactions:** {total_transactions:,}

## Banking Metrics

"""
        
        account_metrics = banking_metrics.get('account_metrics', {})
        if account_metrics:
            md_content += "### Account Distribution\n\n"
            account_dist = account_metrics.get('account_type_distribution', {})
            if account_dist:
                md_content += "| Account Type | Count | Percentage | Avg Balance |\n"
                md_content += "|--------------|-------|------------|-------------|\n"
                
                for acc_type, data in account_dist.items():
                    md_content += f"| {acc_type.title()} | {data.get('count', 0)} | {data.get('percentage', 0)}% | ${data.get('avg_balance', 0):,.2f} |\n"
        
        return md_content
    
    def _make_json_serializable(self, data: Any) -> Any:
        """Convert data to JSON-serializable format."""
        if hasattr(data, 'to_dict'):
            return data.to_dict()
        elif isinstance(data, dict):
            return {k: self._make_json_serializable(v) for k, v in data.items()}
        elif isinstance(data, list):
            return [self._make_json_serializable(item) for item in data]
        elif hasattr(data, 'isoformat'):  # datetime objects
            return data.isoformat()
        else:
            return data